### ISSUE TITLE
Call to a member function getDescription() on array

### ISSUE THREAD

**Issue by fabioaccetta** [yiisoft/yii-gii#10]
### What steps will reproduce the problem?
```bash
$ git clone https://github.com/yiisoft/yii-project-template
```
composer.json:
```json
{
	"name": "yiisoft/yii-project-template",
	[...]
	"require": {
		"yiisoft/yii-dataview": "^3.0@dev",
		"yiisoft/yii-bootstrap4": "^3.0@dev",
		"yiisoft/yii-jquery": "^3.0@dev",
		"yiisoft/yii-console": "^3.0@dev",

		"yiisoft/yii-base-web": "^3.0@dev",

		"yiisoft/cache": "^3.0@dev",
		"yiisoft/di": "^3.0@dev",
		"yiisoft/log": "^3.0@dev",
		"yiisoft/rbac": "^3.0@dev",
		"yiisoft/view": "^3.0@dev"
	},
	"require-dev": {
		"foxy/foxy": "^1.0",
		"yiisoft/yii-debug": "^3.0@dev",
		"yiisoft/yii-gii": "^3.0@dev",
		"hiqdev/composer-config-plugin": "^1.0@dev"
	},
	"extra": {
		"config-plugin": {
			"common": "config/common.php",
			"params": "config/params.php"
		}
	}
}
```

### What's expected?
I expect to see the help description of the `gii/model` help (or any other command)

### What do you get instead?
The error in subject: "Call to a member function getDescription() on array"

### Additional info
Inspecting better the code, I see the error is generaten by [this line 161 in src/console/GenerateController](https://github.com/yiisoft/yii-gii/blob/411daf92b2b4920d89e44aa3ac621dd732ed69da/src/console/GenerateController.php#L161):

```php
$description = $action->generator->getDescription();
```
and infact, as the error says, `$action->generator` is really an array.

I suspect this error comes from the `GenerateController` not implementing `Initiable` interface, because I see in code that the conversion from generator array to object would be done inside `GenerateController::init()`, but this method is never called.

| Q                | A
| ---------------- | ---
| Yii version      | 3.0.x@dev
| PHP version      | 7.1.26
| Operating system | Sabayon Linux

**Comment by rustamwin** [comment]
This issue is outdated. Closing.
