### ISSUE TITLE
Incompatible with validator 2.0

### ISSUE THREAD

**Issue by rossaddison** [yiisoft/yii-gii#129]
### Additional info

| Q                | A
| ---------------- | ---
| Version          | 1.0.?
| PHP version      | 8.1.13
| Operating system | Windows 11

**Comment by ahmadasjad** [comment]
@rossaddison please check now, it must have been resolved

**Comment by vjik** [comment]
Yes, dependencies updated in https://github.com/yiisoft/yii-gii/pull/130
