### ISSUE TITLE
Incorrect regex for ActiveRecord -> tableName

### ISSUE THREAD

**Issue by ahmadasjad** [yiisoft/yii-gii#131]
### What steps will reproduce the problem?
latest master branch commit: 0edd970438b44f04567b6d04cfae9492a5b45227
go to active record generator URL using debug tool similar to http://localhost/debug/gii?generator=active-record
Fill all the required fields, and in the table name field, put any db table name having an underscore like: `employee_punches`

### What is the expected result?
We should see the preview of the ActiveRecord model

### What do you get instead?
Invalid table name

Source code regex: `/^(?:[a-z][a-z0-9]*)(?:\\\\[a-z][a-z0-9]*)*$/i`

### Additional info

| Q                | A
| ---------------- | ---
| Version          | 1.0.?
| PHP version      | 8.1
| Operating system | ubuntu

**Comment by samdark** [comment]
Yes, should include `_`. Do you have some time for a pull request?

**Comment by ahmadasjad** [comment]
Ok, I'll do
