### ISSUE TITLE
Make Gii accessible via Restful API 

### ISSUE THREAD

**Issue by mtangoo** [yiisoft/yii-gii#15]
Right now you have to use Forms to submit information in Gii. That is good, but it would be better if we could do code generation via an API. That will remove the need for Tools (IDEs et al) to be able to generate things using their own “forms” and just POST to API, than now when you have to use ./yii for generating codes automatically.

Using ./yii in code generation is difficult (you have to manage the launched process on different thread to avoid blocking the UI which adds overhead). Also managing response message especially in case of error is difficult.

My Proposal is:
    1. Move all Gii functionalities to REST API
    2. The current UI should be only a front end to that API

The Topic [was discussed here](https://forum.yiiframework.com/t/make-gii-accessible-via-restful-api/126364) before this issue was opened

**Comment by samdark** [comment]
What would API look like?

**Comment by mtangoo** [comment]
Well the same information that Gii sends as form but in JSON format. Am not sure what is going to change in Gii with Yii3, but whatever is sent via the form should be possible with JSON payload

**Comment by samdark** [comment]
> Am not sure what is going to change in Gii with Yii3

Not much conceptually. Gii is a very well done part of Yii 2.

**Comment by mtangoo** [comment]
I think It will be JSON Payload of what is send as form-data right now. I'm not sure how to not duplicate the backend so that the form-data and JSON Payload will share same backend

**Comment by samdark** [comment]
That could be done if frontend is using REST API.

**Comment by ahmadasjad** [comment]
Currently, we are already using the REST API to generate the code. The requirement for this issue is resolved.

FYI: @samdark

**Comment by mtangoo** [comment]
@ahmadasjad can you explain how? I have not dived too much into Yii3 yet, but would love to check how it currently works

**Comment by samdark** [comment]
Thanks, @ahmadasjad
