### ISSUE TITLE
Invalid config

### ISSUE THREAD

**Issue by dzentota** [yiisoft/yii-gii#39]
### What steps will reproduce the problem?
Install this package with a composer

### What is the expected result?
Gii will be auto-discovered by CLI app, so

```bash
./vendor/bin/yii 
```
echos 
```
... 
 gii/controller        Gii controller generator
...
```
### What do you get instead?
Gii command is not registered and is not listed as an available command

### Additional info
The issue is in the wrong config key name:
**Actual**
```php
'console' => [
        'commands' => [
            'gii/controller' => ControllerCommand::class,
        ],
    ],
```
**Expected**
```php
'yiisoft/yii-console' => [
        'commands' => [
            'gii/controller' => ControllerCommand::class,
        ],
    ],
```

| Q                | A
| ---------------- | ---
| Version          | 1.0.?
| PHP version      | 
| Operating system |

**Comment by samdark** [comment]
Fixed. Thanks.
